services:

  svelte-migrations:
    container_name: finances_svelte_migrations
    image: finances-prod:latest
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: "npx prisma migrate deploy"
    networks:
      - internal

  svelte:
    container_name: finances_svelte
    image: finances-prod:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      svelte-migrations:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finances.rule=Host(`finances.thielker.xyz`)"
      - "traefik.http.routers.finances.entrypoints=web, websecure"
    networks:
      - web
      - internal

  postgres:
    container_name: finances_postgres
    image: postgres:15.2
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: finances
    networks:
      - internal
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  web:
    external: true
  internal:
